FROM centos:6.6

MAINTAINER vkyii@foxmail.com


WORKDIR /build

RUN yum -y install gcc kernel-devel \
 #	upgrade gcc/g++
 && curl -O http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-5.2.0/gcc-5.2.0.tar.gz