FROM gliderlabs/alpine:latest

MAINTAINER vkyii@foxmail.com

RUN apk-install bash python3

RUN wget http://repo.continuum.io/archive/Anaconda3-4.0.0-Linux-x86_64.sh \
 && bash Anaconda3-4.0.0-Linux-x86_64.sh